[package]
name = "dependant-view"
version = "1.0.0"
authors = ["Gopiandcode (https://github.com/gopiandcode)"]

[dependencies]

[lib]
name="dependent_view"
path="src/lib.rs"

[[bin]]
name="dependent_view_example"
path="src/main.rs"
